### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#10]
v1.1.0 looks good to me, it works with icons and without, headings look good, just a few of things :-)
1. The ability to turn of/on individual items, perhaps as an array e.g.
   `toolbar: h3, h4, bold, italic, quote, link, image , bullet-list , num-list, hr`
   On some blueprint elements people will want certain buttons but not others?
2. As you are using proper markdown for links when inserted with the link button, it makes sense to also insert proper markdown image links when you select the image button, rather than KirbyText links you currently do. Now I realise people will maybe want the KirbyText for images, so perhaps a kt/md option in the blueprint or two different buttons?
3. Maybe left align the left edge of the toolbar with the left edge of the text, might look a bit neater?
4. Headings in toolbar should be lower case, it is html, and bold button text should be bold as italic text is italic?

All good stuff, keep it up!

**Comment by JonasDoebertin** [comment]
With the rewritten version 1.2.0 getting closer to the finish line (you can [check out the beta release here](https://github.com/JonasDoebertin/kirby-visual-markdown/releases)), let me sum up my thoughts on your suggestions really quick:
1. This will definitely be implemented, soon. Maybe not in this version, but definitely in 1.3.0.
2. I think I will add separate buttons for Markdown images and links and Kirbytext images and links and add a setting to allow hiding one of the options.
3. I kind of like the current style. Moving the toolbar icons to the left looks a bit odd to me.
4. Don't think of the heading buttons as _H1 and H2_ or _H3 and H4_. Think of them as _"Primary Headline"_ and _"Secondary Headline"_. That's the way they're intended to work. Font-Awesome (what the panel uses for all it's icons) just don't has proper icons symboling these two use cases. That's why the _H1_ and _H2_ came in to fill the gap. These two icons will probably be replaced soon.
