### ISSUE TITLE
wrong URL in the readme submodule section

### ISSUE THREAD

**Issue by jbeyerstedt** [JonasDoebertin/kirby-visual-markdown#23]
In the "Git submodule" section of your readme is a wrong URL for cloning.
`git submodule add git@github.com:jonasdoebertin/kirby-visual-markdown.git site/fields/markdown`
should be:
`git submodule add https://github.com/JonasDoebertin/kirby-visual-markdown.git site/fields/markdown`
because not everyone has access rights to your github account.

**Comment by JonasDoebertin** [comment]
The URL itself isn't wrong. Cloning any public repository via SSH works flawlessly, if you have your machine set up to use GitHub with SSH properly. Have a look at this GitHub help article ([Generating SSH keys](https://help.github.com/articles/generating-ssh-keys/)) to see how you can generate a SSH key and attach it to your GitHub account.

I will however still change the url in the readme to the HTTPS url instead, since this works even if you don't have SSH keys set up.

**Thanks for the suggestions!**

**Comment by jbeyerstedt** [comment]
Yes, the URL itself wasn´t wrong, but it is no easy copy paste for all users.

Thanks for your comment on SSH keys. I actually use SSH keys for my server connections, but have not added them to my github account.

Thanks.

**Comment by JonasDoebertin** [comment]
Updated in `develop` branch. Will be merge with the next release.
