### ISSUE TITLE
Suggestion: highlighting for Kirbytext

### ISSUE THREAD

**Issue by malvese** [JonasDoebertin/kirby-visual-markdown#24]
It would be nice to highlight the parenthesis and attributes inside Kirbytext tags, it would be more legible. Especially when parentheses are used in the text. Quick mockup:
![kirbytext](https://cloud.githubusercontent.com/assets/193492/7353878/30f219e2-ed17-11e4-8989-eb70f8d33438.png)

**Comment by JonasDoebertin** [comment]
Great idea! I have been working on this behind the scenes, already :)

One issue though: Afaik, Kirbytext doesn't support parenthesis with Kirbytext tags at the moment. There has been basic support for it in the beta, but it has been dropped due to unstable results.

Considering this and my somewhat limited Regex knowledge, my Kirbytext tags parser/highlighter for CodeMirror doesn't support it either.

**Example of my work-in-progress code in action:**

`(file: myfile.ext text: My dowload title)`

![bildschirmfoto 2015-04-28 um 11 28 45](https://cloud.githubusercontent.com/assets/1367270/7366623/e4406c60-ed99-11e4-876d-bba1bd91fdab.png)

**Comment by malvese** [comment]
Wonderful!
Ha funny, I didn't know and used parenthesis on a site I'm working on. The screenshot is from that site, it runs 2.0.6 and I didn't see any issue so far.

**Comment by JonasDoebertin** [comment]
Using your example Kirbytext tag, the rendering is somewhat broken in the 2.1 beta. The closing brackets are not match correctly (in the rendered output, the closing bracket of (pdf) isn't contained in the anchor tag). Have a look at getkirby/kirby#163 for further reference, too.

Since I honestly don't know a way to make this work properly in the parser (CodeMirror syntax mode) I'm writing to support highlighting of Kirbytext tags, the editor wont support it. 😪

**Comment by JonasDoebertin** [comment]
Fortunately, I found some time to work on it a bit more today and to push the work-in-progress version of the feature up to GitHub. You can find it in the [feature/kirbytext-highlighting branch](https://github.com/JonasDoebertin/kirby-visual-markdown/tree/feature/kirbytext-highlighting) for now.

@malvese I thought you'd like to give it a spin.

**Comment by JonasDoebertin** [comment]
Initial implementation of this feature now arrived in `develop` branch.

**Comment by malvese** [comment]
You're too fast :) I didn't have time to fiddle with it this week, but on Monday I'll upgrade the site I'm working on.

**Comment by malvese** [comment]
I just saw you seem to have used the colors from my screenshot. It was just a quick test, I actually think the bold grey attribute name is not very legible. Also the bright red parenthesis looks a bit like an error.
May I suggest a slightly different style?

``` css
.cm-s-visualmarkdown .cm-kirbytext-attribute {
  /* font-weight: bold; */
  color: #89939A;
}

.cm-s-visualmarkdown .cm-kirbytext-open, .cm-s-visualmarkdown .cm-kirbytext-close {
  font-weight: bold;
  color: #F07642;
}
```

![syntaxcolors](https://cloud.githubusercontent.com/assets/193492/7541088/d9097078-f5b2-11e4-9520-4fcc3fb4b373.png)

---

We could also go crazy.

Attribute bubble, better visual distinction between attributes, but a bit over-the-top perhaps ^_^
![syntaxcolors2](https://cloud.githubusercontent.com/assets/193492/7541514/5a82b7a6-f5b6-11e4-83a4-818d9813fbaf.png)

Value 'field':
![syntaxcolors3](https://cloud.githubusercontent.com/assets/193492/7541516/5a85da08-f5b6-11e4-9673-35bd2d40a8d3.png)
But doesn't work well in multiline…
![syntaxcolors4](https://cloud.githubusercontent.com/assets/193492/7541515/5a83f9f4-f5b6-11e4-8262-5cc9337a9ca8.png)

**Comment by JonasDoebertin** [comment]
I changed the colors a little bit to make them adapt colors from the Kirby Panel patternlab since I liked the idea to make the kirbytext tags represent the Kirby brand colors.

Your "crazy" styles actually work really well for short (and single line) tags!
Once the tags are longer or have a line break within them it's not that appealing to me though.
