### ISSUE TITLE
Does not adjust to 'strict markdown mode' in Kirby 2.1.0 

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#30]
With Kirby 2.1.0, Visual Markdown does not seem to honour the Markdown mode e.g. no kirby tags?

Kirby 2.1.0 update notes:
"You can now set the panel to strict markdown mode by switching off kirbytext tag support in your config:
c::set('panel.kirbytext', false);"

**Comment by JonasDoebertin** [comment]
I know about this new feature and I definitely have it on my todo list to make the editor respect that setting and generate plain markdown link and image tags when it is active.

This will be added with the next update.

**Comment by shoesforindustry** [comment]
Thanks Jonas, I thought you'd have it in hand ;-)
Don't mean to be pushy, but any you idea on time scales for this update, just I'm mid-project and really want to use this plugin, but strict Markdown is a requirement. It seemed to work in an earlier version but that may have just been me, or the caches....

**Comment by JonasDoebertin** [comment]
In an earlier version, the editor was always generating plain markdown for links and images. Due to popular demand I changed it to kirbytext.

To make the editor generate markdown, you may want to add this fix, in the meantime:

Modify the file `assets/js/visualmarkdowneditor.js` and change line 85 to 90 from this:

``` js
link: function () {
    self.insertAround('(link: http:// text: ', ')');
},
image: function () {
    self.insertBefore('(image: filename.jpg)');
},
```

to this:

``` js
link: function () {
    self.insertAround('[', '](http://)');
},
image: function () {
    self.insertBefore('![image description](http://)');
},
```

That should do the trick for now.

Please keep in mind that you have to use absolute URLs for all plain markdown tags.

---

PS: If you want to have a minor update release to support this by tomorrow afternoon, you might want to sponsor the update by [purchasing a moral license](https://gumroad.com/l/visualmarkdown) for the editor 😉

**Comment by shoesforindustry** [comment]
Thanks very much for that Jonas, it for a students site, so not for profit. But to encourage you to release a small update I have bought a small ‘beer money’ moral license, hope it encourages you :-)

Let me know when it’s released.

Russ

**Comment by JonasDoebertin** [comment]
Wow, thank you so much! I'll work on the update first thing tomorrow!

**Comment by shoesforindustry** [comment]
Also it would appear you can do relative links with Markdown e.g.

[Link to About](/about)
or
[Link to Privacy](/about/privacy)

Code produced
<li><a href="/about <view-source:http://jimmydean.dev/about>">Link to About</a></li>
<li><a href="/about/privacy <view-source:http://jimmydean.dev/about/privacy>">Link to Privacy </a></li>

Russ

**Comment by JonasDoebertin** [comment]
Yeah, my fault. Of course you can do relative urls.

What I meant is that Kirby will convert relative URLs (to resources in the content folder) in Kirbytext tags to absolute URLs automagically for you in most cases. This doesn't work wirk plain markdown.

So when adding images, you'd have to specify the whole URL, because the image URL path `/content/1-a-page/1-a-sub-page/image.jpg` you have to use isn't the same as the pages URL path `/a-page/a-sub-page`.

**Comment by shoesforindustry** [comment]
Sorry I’m a little confused about the images stuff?

If I drag in an uploaded image in I get:
![image name](http://domain.dev/content/2-projects/4-project-name/image name.jpg)

Which converts to:
<img src=“http://jimmydean.dev/content/2-projects/4-project-name/image name.jpg” alt=“image name" /\>

Is this wrong, it seems to work, at least locally?

Russ

**Comment by JonasDoebertin** [comment]
That's completely right, that way! Seems Kirby does the magic when while dragging and dropping. :-)

What I was trying to say is that image URLs always have to include the `content/` url part and the full directory names of your content structure. In this, they differ from the pages urls.

**Comment by JonasDoebertin** [comment]
I just tagged a [1.3.1 release](https://github.com/JonasDoebertin/kirby-visual-markdown/releases/tag/1.3.1) that respects the _strict markdown mode_ setting.

Thanks again for your support!
